<section class="section-home-disclaimer section">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-xl-8">
        <p>The charts above cover the period from inception (June 28, 2011) of Tarkio Fund (the “fund” or “TARKX”) to September 28, 2018. Performance information quoted above represents past performance and does not guarantee future results. The investment return and principal value of an investment in the fund will fluctuate so that an investor’s shares, when redeemed, may be worth more or less than their original cost. Current performance may be lower or higher than the performance information quoted above. Performance figures assume reinvestment of dividends and capital gains. Most recent month-end performance and answers to any questions you may have can be obtained by calling Mutual Shareholder Services at (866) 738-3629. The S&P 500 Index is a broad based measurement of changes in the stock market, is used for comparative purposes only, and is not meant to be indicative of the fund’s performance, asset composition, or volatility. Given the wide scope of securities held by the S&P 500 Index, it should be inherently less volatile. Our results may differ markedly from those of the S&P500 Index in either up or down market trends. The performance of the S&P 500 Index is shown with all dividends reinvested into the index and does not reflect any reduction in performance for the effects of transactions costs or management fees. Investors cannot invest directly in an index. The expense ratio of the fund is 1.00%. The expense ratio includes acquired fund fees and expenses which are incurred indirectly by the fund as a result of investments in securities issued by one or more investment companies. For a more complete discussion of the risks associated with the fund please see the "Risks" tab of this site or read the most recent prospectus.</p>
        <p>Please consider the investment objectives, risks and charges and expenses of the fund carefully before investing.  The fund’s prospectus contains this and other information about the fund and is available on this website or by calling (866) 738-3629.  Please read the prospectus carefully before investing. An investment in the fund is not a deposit of a bank and is not insured or guaranteed by the Federal Deposit Insurance Corporation or any other government agency. The fund may be offered only to persons in the United States and by way of a prospectus. This website should not be considered a solicitation or offering of any product or service to investors residing outside of the United States.</p>
        <p>Past performance in not indicative of future performance. The S&P 500 Index is an umanaged capitalization weighted index of the common stocks of 500 major US corporations.</p>
        <p>The investment return and principal value of an investment in the fund will fluctuate so that an investor's share, when redeemed, may be worth more or less than their original cost. Current performance may be lower or higher than the performance data quoted.</p>
        <p>Starting at 1.25% upon fund inception (6/28/2011) the expense ratio was reduced, on a voluntary basis, by the fund's investment advisor (Front Street Capital Management, Inc.) to 1.0% which is where the fund's expense ratio currently remains.</p>
        <p>Year to date performance as of the most recent month end can be obtained by calling Mutual Shareholder Services at 1-866-738-3629.</p>
        <p>Investing in the fund involves risk. Investors should carefully review the risks associated with an investment in the fund by reading the prospectus which can be found <a href="https://docs.wixstatic.com/ugd/b521eb_b94a2a9a5b43449b84d9795b6b34f851.pdf">here</a>, and understand those risks before investing.</p>
        <p>Tarkio Fund is distributed by Arbor Cour Capital, LLC - Member <a href="https://brokercheck.finra.org/">FINRA</a></p>
      </div>
    </div>
  </div>
</section>
